# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Code by Numbers
tagline:          'A Coding Blog'
description:      'Capturing the cool and useful things I find on my coding adventures in the Cloud'
url:              http://mikestokes.co
baseurl:          /

author:
  name:           'Mike Stokes'
  url:            http://mikestokes.co

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mikestokes
