# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mike Stokes
tagline:          'A Jekyll theme'
description:      'A blog by a coder who loves tech and is lucky enough to play in his sandpit with it every day.'
url:              http://mikestokes.co
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mikestokes
