# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Code Maverick
tagline:          'A Coding Blog'
description:      'Capturing the coolest things I find on my Cloud Coding Adventures... so that you don''t have to!'
url:              http://mikestokes.co
baseurl:          /

author:
  name:           'Mike Stokes'
  url:            http://mikestokes.co
  linkedin:       http://nz.linkedin.com/in/themikestokes

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mikestokes
