# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mike Stokes
tagline:          'A Jekyll theme'
description:      'A blog by a developer who loves technology and is lucky enough to play with it on a daily basis.'
url:              http://mikestokes.co
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mikestokes
